# Generated by Django 5.0.6 on 2024-06-25 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_account_profile_image'),
    ]

    operations = [
    ]
