# Generated by Django 5.0.6 on 2024-07-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_privacypolicysection_account_agree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='agree',
            field=models.BooleanField(),
        ),
    ]
