# Generated by Django 5.0.6 on 2024-07-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_account_agree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='agree',
            field=models.BooleanField(default=False),
        ),
    ]
