# Generated by Django 5.0.6 on 2024-07-17 13:02

import django.db.models.deletion
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_date', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_key', models.CharField(max_length=50)),
                ('answer', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('questionnaire_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='patients.questionnaireresponse')),
            ],
        ),
    ]
