# Generated by Django 5.0.6 on 2024-07-18 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='answer',
        ),
    ]
