# Generated by Django 5.0.6 on 2024-07-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_remove_response_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaireresponse',
            name='progress',
            field=models.FloatField(db_default=0),
        ),
    ]
