# Generated by Django 5.0.6 on 2024-07-24 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_questionnaireresponse_progress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.CharField(max_length=20)),
                ('risk_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('probability_benign', models.DecimalField(decimal_places=2, max_digits=5)),
                ('probability_malignant', models.DecimalField(decimal_places=2, max_digits=5)),
                ('chart_data', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('questionnaire_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.questionnaireresponse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
