# Generated by Django 5.0.6 on 2024-07-24 16:26

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_predictionresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionresult',
            name='submission_date',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
        ),
        migrations.AlterField(
            model_name='predictionresult',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now()),
        ),
    ]
