# Generated by Django 5.0.6 on 2024-07-24 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_predictionresult_submission_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionresult',
            name='dob',
            field=models.DateField(null=True, verbose_name='Birthday'),
        ),
    ]
