# Generated by Django 5.0.6 on 2024-07-26 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_predictionresult_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionresult',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
