# Generated by Django 5.0.6 on 2024-07-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_predictionresult_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaireresponse',
            name='state',
            field=models.CharField(choices=[('Initiate', 'Initiate'), ('Start', 'Start'), ('Complete', 'Complete')], default='Initiate', max_length=10),
        ),
    ]
