# Generated by Django 5.0.6 on 2024-07-30 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_contact_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
