# Generated by Django 5.0.6 on 2024-07-30 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_contact_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='subject',
        ),
    ]
