# Generated by Django 5.0.6 on 2024-08-10 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0013_contact_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='state',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
